export const POST_MESSAGE = "POST_MESSAGE";
export const POST_MESSAGE_SUCCESSFUL = "POST_MESSAGE_SUCCESSFUL";
export const POST_MESSAGE_FAILED = "POST_MESSAGE_FAILED";

export const SET_PROFILE = "SET_PROFILE";
export const SET_PROFILE_SUCCESSFUL = "SET_PROFILE_SUCCESSFUL";
export const SET_PROFILE_FAILED = "SET_PROFILE_FAILED";
